## Coletando a base de dados
Wireless Indoor Localization Data Set

https://archive.ics.uci.edu/ml/datasets/Wireless+Indoor+Localization#


In [1]:
!ls

sample_data


In [2]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00422/wifi_localization.txt

--2021-08-03 13:33:37--  https://archive.ics.uci.edu/ml/machine-learning-databases/00422/wifi_localization.txt
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 62000 (61K) [application/x-httpd-php]
Saving to: ‘wifi_localization.txt’

wifi_localization.t 100%[===================>]  60.55K  --.-KB/s    in 0.1s    

2021-08-03 13:33:38 (466 KB/s) - ‘wifi_localization.txt’ saved [62000/62000]



In [3]:
!head wifi_localization.txt

-64	-56	-61	-66	-71	-82	-81	1
-68	-57	-61	-65	-71	-85	-85	1
-63	-60	-60	-67	-76	-85	-84	1
-61	-60	-68	-62	-77	-90	-80	1
-63	-65	-60	-63	-77	-81	-87	1
-64	-55	-63	-66	-76	-88	-83	1
-65	-61	-65	-67	-69	-87	-84	1
-61	-63	-58	-66	-74	-87	-82	1
-65	-60	-59	-63	-76	-86	-82	1
-62	-60	-66	-68	-80	-86	-91	1


In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
data = np.loadtxt('wifi_localization.txt')

In [7]:
data.shape

(2000, 8)

In [8]:
data

array([[-64., -56., -61., ..., -82., -81.,   1.],
       [-68., -57., -61., ..., -85., -85.,   1.],
       [-63., -60., -60., ..., -85., -84.,   1.],
       ...,
       [-62., -59., -46., ..., -87., -88.,   4.],
       [-62., -58., -52., ..., -90., -85.,   4.],
       [-59., -50., -45., ..., -88., -87.,   4.]])

In [9]:
cols_wifi_nomes = [f'wifi_{i+1}' for i in range(7)]
cols_wifi_nomes

['wifi_1', 'wifi_2', 'wifi_3', 'wifi_4', 'wifi_5', 'wifi_6', 'wifi_7']

In [10]:
data_df = pd.DataFrame(data, columns=cols_wifi_nomes+['sala'])

In [11]:
data_df

wifi_1  wifi_2  wifi_3  wifi_4  wifi_5  wifi_6  wifi_7  sala
0      -64.0   -56.0   -61.0   -66.0   -71.0   -82.0   -81.0   1.0
1      -68.0   -57.0   -61.0   -65.0   -71.0   -85.0   -85.0   1.0
2      -63.0   -60.0   -60.0   -67.0   -76.0   -85.0   -84.0   1.0
3      -61.0   -60.0   -68.0   -62.0   -77.0   -90.0   -80.0   1.0
4      -63.0   -65.0   -60.0   -63.0   -77.0   -81.0   -87.0   1.0
...      ...     ...     ...     ...     ...     ...     ...   ...
1995   -59.0   -59.0   -48.0   -66.0   -50.0   -86.0   -94.0   4.0
1996   -59.0   -56.0   -50.0   -62.0   -47.0   -87.0   -90.0   4.0
1997   -62.0   -59.0   -46.0   -65.0   -45.0   -87.0   -88.0   4.0
1998   -62.0   -58.0   -52.0   -61.0   -41.0   -90.0   -85.0   4.0
1999   -59.0   -50.0   -45.0   -60.0   -45.0   -88.0   -87.0   4.0

[2000 rows x 8 columns]

In [12]:
data_df['sala'] = data_df['sala'].astype('object')

In [13]:
data_df.dtypes

wifi_1    float64
wifi_2    float64
wifi_3    float64
wifi_4    float64
wifi_5    float64
wifi_6    float64
wifi_7    float64
sala       object
dtype: object

In [14]:
data_df

wifi_1  wifi_2  wifi_3  wifi_4  wifi_5  wifi_6  wifi_7 sala
0      -64.0   -56.0   -61.0   -66.0   -71.0   -82.0   -81.0    1
1      -68.0   -57.0   -61.0   -65.0   -71.0   -85.0   -85.0    1
2      -63.0   -60.0   -60.0   -67.0   -76.0   -85.0   -84.0    1
3      -61.0   -60.0   -68.0   -62.0   -77.0   -90.0   -80.0    1
4      -63.0   -65.0   -60.0   -63.0   -77.0   -81.0   -87.0    1
...      ...     ...     ...     ...     ...     ...     ...  ...
1995   -59.0   -59.0   -48.0   -66.0   -50.0   -86.0   -94.0    4
1996   -59.0   -56.0   -50.0   -62.0   -47.0   -87.0   -90.0    4
1997   -62.0   -59.0   -46.0   -65.0   -45.0   -87.0   -88.0    4
1998   -62.0   -58.0   -52.0   -61.0   -41.0   -90.0   -85.0    4
1999   -59.0   -50.0   -45.0   -60.0   -45.0   -88.0   -87.0    4

[2000 rows x 8 columns]

In [15]:
data_df.describe()

wifi_1       wifi_2  ...       wifi_6       wifi_7
count  2000.000000  2000.000000  ...  2000.000000  2000.000000
mean    -52.330500   -55.623500  ...   -80.985000   -81.726500
std      11.321677     3.417688  ...     6.516672     6.519812
min     -74.000000   -74.000000  ...   -97.000000   -98.000000
25%     -61.000000   -58.000000  ...   -86.000000   -87.000000
50%     -55.000000   -56.000000  ...   -82.000000   -83.000000
75%     -46.000000   -53.000000  ...   -77.000000   -78.000000
max     -10.000000   -45.000000  ...   -61.000000   -63.000000

[8 rows x 7 columns]

In [16]:
data_df['sala'].value_counts()

4.0    500
3.0    500
2.0    500
1.0    500
Name: sala, dtype: int64

In [17]:
X = data[:,:-1]
print(X.shape)
print(X)

(2000, 7)
[[-64. -56. -61. ... -71. -82. -81.]
 [-68. -57. -61. ... -71. -85. -85.]
 [-63. -60. -60. ... -76. -85. -84.]
 ...
 [-62. -59. -46. ... -45. -87. -88.]
 [-62. -58. -52. ... -41. -90. -85.]
 [-59. -50. -45. ... -45. -88. -87.]]


In [18]:
y = data[:,-1]
y = y.astype('int8')
print(y.shape)
print(y.dtype)
print(y)

(2000,)
int8
[1 1 1 ... 4 4 4]


### Conjuntos de treino e teste

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=27)

In [21]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1600, 7)
(400, 7)
(1600,)
(400,)


In [22]:
pd.DataFrame(X_train, columns=cols_wifi_nomes).describe()

wifi_1       wifi_2  ...       wifi_6       wifi_7
count  1600.000000  1600.000000  ...  1600.000000  1600.000000
mean    -52.087500   -55.640625  ...   -80.982500   -81.711875
std      11.335294     3.444218  ...     6.550211     6.583859
min     -73.000000   -74.000000  ...   -97.000000   -98.000000
25%     -61.000000   -58.000000  ...   -86.000000   -87.000000
50%     -53.000000   -56.000000  ...   -82.000000   -83.000000
75%     -45.750000   -53.000000  ...   -77.000000   -78.000000
max     -10.000000   -45.000000  ...   -62.000000   -63.000000

[8 rows x 7 columns]

In [23]:
pd.DataFrame(y_test, columns=['y'])['y'].value_counts()

1    128
2     92
4     91
3     89
Name: y, dtype: int64

### Ajuste dos valores numéricos. Reescala linear.

In [24]:
from sklearn.preprocessing import MinMaxScaler

In [25]:
X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

In [26]:
pd.DataFrame(X_train, columns=cols_wifi_nomes).describe()

wifi_1       wifi_2  ...       wifi_6       wifi_7
count  1600.000000  1600.000000  ...  1600.000000  1600.000000
mean      0.331944     0.633082  ...     0.457643     0.465375
std       0.179925     0.118766  ...     0.187149     0.188110
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.190476     0.551724  ...     0.314286     0.314286
50%       0.317460     0.620690  ...     0.428571     0.428571
75%       0.432540     0.724138  ...     0.571429     0.571429
max       1.000000     1.000000  ...     1.000000     1.000000

[8 rows x 7 columns]

Vamos fazer o ajuste para One-Hot dos dados das classes. 
Temos 4 classes (Salas 1,2,3 e 4). 

In [27]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

In [28]:
y_train

array([1, 2, 2, ..., 4, 4, 3], dtype=int8)

In [29]:
y_train.shape

(1600,)

In [30]:
to_categorical(y_train)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.]], dtype=float32)

In [31]:
to_categorical(y_train)[:,0].sum()

0.0

Isso aconteceu pois nossas classes começam do 1, e não do zero.

Para não modificar a lógica, vamos desconsiderar a coluna 0.

In [32]:
to_categorical(y_train)[:,1:]

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]], dtype=float32)

In [33]:
y_train = to_categorical(y_train)[:,1:]
y_test = to_categorical(y_test)[:,1:]

In [34]:
print(y_train.shape)
print(y_test.shape)

(1600, 4)
(400, 4)


## Criando uma Rede Neural MLP

Vamos usar o modelo **sequencial** do Tensorflow-Keras para criar nossa primeira MLP. 

In [35]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [36]:
tf.__version__

'2.5.0'

In [37]:
model = keras.Sequential(name="PrimeiraMLP")
model.add(keras.Input(shape=(7,))) 
model.add(layers.Dense(10, activation="sigmoid"))
model.add(layers.Dense(4, activation="softmax"))


In [38]:
model.layers

In [39]:
model.layers[0].weights

[<tf.Variable 'dense/kernel:0' shape=(7, 10) dtype=float32, numpy=
 array([[ 0.29897356,  0.51519156, -0.04941881, -0.09085411,  0.22049314,
         -0.5089749 ,  0.45328188,  0.34458238,  0.23552561, -0.04035866],
        [-0.45222217,  0.35921055, -0.49403736,  0.29305875,  0.13564849,
          0.01886469,  0.09125102, -0.56570935, -0.5712348 , -0.01887602],
        [-0.04242879,  0.00814992,  0.42095625,  0.18546683, -0.2572145 ,
          0.3022523 , -0.18428668, -0.18133587,  0.4370401 ,  0.5472851 ],
        [-0.10850805, -0.16299453, -0.34798446,  0.05525017,  0.48527074,
         -0.5813023 ,  0.50225663, -0.16939148, -0.49182746, -0.25237033],
        [ 0.24494785,  0.389292  ,  0.02189285, -0.09536499, -0.27494392,
          0.3617761 , -0.32653198, -0.36475033, -0.47300398,  0.02812934],
        [ 0.15144646, -0.4973179 ,  0.59092045,  0.28681195,  0.02283829,
         -0.1360299 ,  0.11253011, -0.27268684,  0.56143296,  0.5381293 ],
        [ 0.28369612,  0.53612876, -0.0

In [40]:
model.summary()

Model: "PrimeiraMLP"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                80        
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 44        
Total params: 124
Trainable params: 124
Non-trainable params: 0
_________________________________________________________________


### Treinamento da rede neural

In [41]:
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

In [42]:
model.fit(X_train, y_train, epochs=20, batch_size=8)

Epoch 1/20
200/200 [==============================] - 1s 1ms/step - loss: 1.4611 - accuracy: 0.2556
Epoch 2/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3775 - accuracy: 0.3475
Epoch 3/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3678 - accuracy: 0.4137
Epoch 4/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3605 - accuracy: 0.4650
Epoch 5/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3529 - accuracy: 0.4475
Epoch 6/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3447 - accuracy: 0.4594
Epoch 7/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3362 - accuracy: 0.5163
Epoch 8/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3273 - accuracy: 0.5163
Epoch 9/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3168 - accuracy: 0.5644
Epoch 10/20
200/200 [==============================] - 0s 1ms/step - loss: 1.3067 - accuracy: 0.5875

In [43]:
_, accuracy = model.evaluate(X_test, y_test, batch_size=32)
print('Accuracy: %.2f' % (accuracy*100))

13/13 [==============================] - 0s 2ms/step - loss: 1.1559 - accuracy: 0.6700
Accuracy: 67.00


In [44]:
# acessando os pesos de uma camada:
model.layers[0].weights

[<tf.Variable 'dense/kernel:0' shape=(7, 10) dtype=float32, numpy=
 array([[ 0.3540699 ,  0.26791897, -0.33877757, -0.07783026,  0.38250858,
         -0.88188857,  0.95124084,  0.2696551 ,  0.19488078, -0.3813933 ],
        [-0.41796264,  0.3047694 , -0.5329979 ,  0.29507336,  0.08599947,
          0.10510002, -0.05416804, -0.5331807 , -0.5551795 , -0.0576626 ],
        [ 0.36942083, -0.28956738,  0.36188772, -0.09001373, -0.58021677,
          0.38733837, -0.04126663, -0.06674012,  0.50769806,  0.7884722 ],
        [-0.04138654, -0.4140745 , -0.63247526,  0.06086585,  0.63078666,
         -0.9383839 ,  0.9860062 , -0.23741524, -0.5282717 , -0.57772475],
        [ 0.68593144,  0.23669338,  0.23874256, -0.6996215 , -0.70532304,
          0.6188074 , -0.3652987 , -0.23972014, -0.4511137 ,  0.60917765],
        [-0.05279829, -0.54070824,  0.3844957 ,  0.3968322 ,  0.35663137,
         -0.47222844,  0.36128983, -0.4018844 ,  0.4646523 ,  0.07511452],
        [ 0.1108719 ,  0.48587045, -0.2

Note a relação entre o batch size e os passos (steps), tanto no treino quanto no teste.

teto(#treino/#batch) = #steps